name: "Set Version from Tag"
description: "Extracts version from git tag and updates Cargo.toml (maturin converts to PEP 440 automatically)"
outputs:
  version:
    description: "The extracted version"
    value: ${{ steps.extract.outputs.VERSION }}
runs:
  using: "composite"
  steps:
    - name: Extract version from tag
      id: extract
      shell: bash
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        # Convert PEP 440 to SemVer for Cargo: 0.1.0b1 -> 0.1.0-beta.1
        CARGO_VERSION=$(echo "$VERSION" | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+)b([0-9]+)/\1-beta.\2/')
        echo "CARGO_VERSION=$CARGO_VERSION" >> $GITHUB_OUTPUT

    - name: Update version in Cargo.toml
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          sed -i '' 's/^version = ".*"/version = "${{ steps.extract.outputs.CARGO_VERSION }}"/' py-commol/Cargo.toml
        else
          sed -i 's/^version = ".*"/version = "${{ steps.extract.outputs.CARGO_VERSION }}"/' py-commol/Cargo.toml
        fi
