repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/python-poetry/poetry
    rev: "2.2.0"
    hooks:
      - id: poetry-check
        files: ^py-commol/pyproject\.toml$
        args: ["-C", "py-commol"]
      - id: poetry-lock
        files: ^py-commol/pyproject\.toml$
        args: ["-C", "py-commol"]
